config/routes.rb
TreeHouse::Application.routes.draw do
  resources :donations

  resources :works

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'site#home'

  match '/testsub', to: 'site#testsub', via: 'get'
  match '/subscribe', to: 'site#subscribe', via: 'get'
  match '/subscribe_email', to: 'site#subscribe_email', via: 'post'
  match '/unsubscribe' , to: 'site#unsubscribe', via: 'get'
  match '/unsubscribe_email', to: 'site#unsubsribe_email', via: 'post'
    match '/published', to: 'site#published',    via: 'get'
    match '/photography', to: 'site#photography', via: 'get'
      match '/photography/:series_name', to: 'site#photography_detail', via: 'get'
      match '/photo/:series_name/:name', to: 'site#photo', via: 'get'

    match '/painting', to: 'site#painting', via: 'get'
      match '/painting/:name', to: 'site#painting_detail', via: 'get'

    match '/drawing', to: 'site#drawing', via: 'get'

    match '/parastories', to: 'site#parastories', via: 'get'
      match '/parastories/:name', to: 'site#parastories', via: 'get'

    match '/shortstories', to: 'site#shortstories', via: 'get'
      match '/shortstories/:name', to: 'site#short_detail', via: 'get'

    match '/poetry', to: 'site#poetry', via: 'get'
      match '/poetry/:name', to: 'site#poetry_detail', via: 'get'

    match '/thankyou', to: 'site#thankyou', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  # => Constants
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PWD_REGEX = /\A(?=.*[a-zA-Z])(?=.*[0-9]).{8,}\z/  # minimum 8 characters, must contain 1 letter and 1 number
  
  # => Password infrastructure
  has_secure_password
  
  has_many :works
  
  validates :email,
            presence: true,
            length: { maximum: 50 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
            
  
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  
  validates :password, length: { minimum: 8 },
                       format: { with: VALID_PWD_REGEX },
                       if: :validate_password?
                       
  
  # => Callbacks
  before_save { self.email = email.downcase }
  before_create :create_session_key
  
  # => Class methods
  def User.new_session_key
    SecureRandom.urlsafe_base64
  end
  
  def User.encrypt(key)
    Digest::SHA1.hexdigest(key.to_s)
  end
  
  def send_welcome_email
    begin
      welcome = UserMailer.welcome_email(self)
      welcome.deliver
    rescue
      logger.error welcome.errors.inspect
    end
  end
  
  # => Private methods
  private
    def create_session_key
      self.session_key = User.encrypt(User.new_session_key)
    end
    
    def validate_password?
      password.present? || password_confirmation.present?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new()
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      
      @user.send_welcome_email
      
      sign_in @user
      flash[:notice] = "Welcome to the Fuinneamh!"
      redirect_to root_path
    else
      flash[:failure] = "Could not create user!"
      render 'new'
    end
  end
  
  def get_user_image
    @user = User.find(params[:id])
    unless @user.image.nil?
      unless File.exists? Rails.root.join('public', 'uploads', @user.id.to_s)
        File.open(Rails.root.join('public', 'uploads', @user.id.to_s), 'wb') do |file|
          file.write(@user.image)
        end
      end
      
      send_file Rails.root.join('public', 'uploads', @user.id.to_s), :type => 'image/jpeg', :disposition => 'inline'
    else
      send_file Rails.root.join('public', 'generic_user_image.png'), :type => 'image/jpeg', :disposition => 'inline'
    end
  end
  
  def show
    @user = User.find(params[:id])
    @popular = @user.works.order(read_count: :desc).first
  end
  
  def update
    @user = User.find(params[:id])
    
    uploaded = params[:user][:image]
    
    unless uploaded.nil?
      uploaded_content = uploaded.read
      @user.update_attribute(:image, uploaded_content)
      
      File.open(Rails.root.join('public', 'uploads', @user.id.to_s), 'wb') do |file|
        file.write(uploaded_content)
      end
    end
    
    if user_params[:password].blank?
      user_params.delete('password')
      user_params.delete('password_confirmation')
    end
    
    if @user.update_attributes(user_params)
      redirect_to @user, notice: "Successfully updated your Profile!"
    else
      logger.debug @user.errors.messages.inspect
      render 'edit'
    end
    
  end
  
  def edit
    if signed_in?
      @user = current_user
    else
      @user = User.find(params[:id])
      redirect_to @user
    end
  end
  
  def stories
    if !signed_in?
      redirect_to search_path
    end
    
    @user = current_user
    @works = @user.works
  end
  
  private
  
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :bio)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def recieved(in_id)
    don = Donation.where(user_id: in_id, approved: true)
    
    unless don.empty?
      don.sum(:amount).to_s
    else
      ''
    end
  end
  
  def donated(in_id)
    user = User.find(in_id)
    
    unless user.nil?
      user.donated.to_s
    else
      0.0
    end
  end
  
  # => Emits the tag for a user's gravatar
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=100"
    image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
  end
  
  def profile_image(user_id)
    image_tag url_for controller: 'users', action: 'get_user_image', type: 'image/jpeg', id: user_id
  end
  
  def profile_image_small(user_id)
    ('<img src="' + image_url(user_id) + '" style="height: 60px;">').html_safe
  end
  
  def image_url(user_id)
    url_for controller: 'users', action: 'get_user_image', type: 'image/jpeg', id: user_id
  end
      
end

app/views/users/_user_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_description" style="display: none;">
    <div class="alert alert-error">
      There are <%= pluralize(@user.errors.count, "error") %>.
    </div>
    
    <ul>
    	<% @user.errors.full_messages.each do |msg| %>
    		<li>* <%= msg %></li>
    	<% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user_follow_small.html.erb
<div class="content-panel half-height">
	<h1>Followization</h1>
</div>

app/views/users/_user_messages_small.html.erb
<div class="content-panel half-height">
	<h1>Messages SM</h1>
</div>

app/views/users/_user_profile_small.html.erb
<div class="content-panel half-height">
	<div class="floating-grid3 profile-top">
		<div class="cell">
			<%= gravatar_for @user %>
		</div>
		<div class="cell">
			<h2><%= @user.first_name %> <%= @user.last_name %></h2>
			<%= mail_to @user.email %>
		</div>
	</div>
	
	<div><%= @user.bio %></div>
</div>

app/views/users/_user_stats_small.html.erb
<div class="content-panel half-height">
	<h1>Stats SM</h1>
</div>

app/views/users/_user_stories.html.erb
<div class="content-panel">
	<h1>Stories</h1>
	<%= link_to "Post a Story", new_work_path, class: "btn btn-large"%>
	<% @user.works.each do |w| %>
		<div class="floating-grid2">
			<div class="cell">
				<%= w.title %>
			</div>
			<div class="cell" style="text-align: right;">
				<%= w.read_count %>
			</div>
		</div>
	<% end %>
</div>

app/views/users/_user_whats_new.html.erb
<div class="content-panel">
	<h1>Tailored What's New</h1>
</div>

app/views/users/edit.html.erb
<% provide(:title, @user.first_name + ' ' + @user.last_name)%>
<%= page_title_tag "myprofileeditgraphx.png"%>

<%= form_for(@user) do |f| %>
	<div class="floating-grid3">
		<div class="cell">
			<!-- Profile photo -->
			<div class="content-panel">
				<%= profile_image @user.id %><br />
				<div>
					<%= f.file_field :image, class: 'centered' %>
				</div>
			</div>
			
			<!-- User Bio -->
			<div class="content-panel">
				<%= f.text_area :bio, style: 'width: 100%;'%>
			</div>
		</div>
		<div class="cell">
			<!-- Pen Name -->
			<div class="content-panel">
				<div class="form-row"><%= f.label :first_name, 'First Name', class: 'form-label' %><%= f.text_field :first_name, class: 'form-input'%></div>
				<div class="form-row"><%= f.label :last_name, 'Last Name', class: 'form-label' %><%= f.text_field :last_name, class: 'form-input'%></div>
				<div class="form-row"><%= f.label :email, 'Email', class: 'form-label' %><%= f.text_field :email, class: 'form-input'%></div>
			</div>
			
			<!-- User Since -->
			<div class="content-panel">
				User Since <%= @user.created_at.year %>
			</div>
			
			<!-- Stories -->
			<div class="content-panel">
				<% if signed_in? %>
					<a href="<%= stories_path %>"><%= image_tag "MyStories.png" %></a>
				<% else %>
					<a href="/search?author=<%= @user.id %>"><%= image_tag "PostStory.png"%></a>
				<% end %>
			</div>
		</div>
		
		
		<div class="cell">
			<!-- User stats -->
			<div class="content-panel">
				<div>Stories Published: <%= @user.works.length %></div>
				<div>Total Reads: <%= @user.works.sum(:read_count) %></div>
				<div>Amount Donated: </div>
				<div>Amount Recieved: </div>
			</div>
			
			<!-- Donate -->
			<div class="content-panel">
				<a href="#"><%= image_tag "Donate.png"%></a>
			</div>
			
			<div class="content-panel">
				<div class="col-xs-6"><%= f.submit "Save", class: "centered btn btn-large bttn" %></div>
				<div class="col-xs-1"></div>
				<div class="col-xs-4"><%= link_to "Cancel", @user, class: "centered btn btn-large bttn",style: "color: #bad2ad; font-family: 'Spinnaker, sans-serif'" %></div>
			</div>
		</div>
	<% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Signup')%>
<%= page_title_tag "Joingraphx.png" %>
<div class="row">
	<div class="col-lg-4 col-md-5 col-sm-6 col-xs-6 centered content-panel">
		<%= form_for(@user) do |f| %>
		
			<%= render 'users/user_error_messages' %>
		
			<div class="form-row">
				<%= f.label :first_name, "First Name", class: "form-label" %>
				<%= f.text_field :first_name, class: "form-input"%>
			</div>
			
			<div class="form-row">
				<%= f.label :last_name, "Last Name", class: "form-label" %>
				<%= f.text_field :last_name, class: "form-input" %>
			</div>
			
			<div class="form-row">
				<%= f.label :email, "Email", class: "form-label" %>
				<%= f.text_field :email, class: "form-input" %>
			</div>
			
			<div class="form-row">
				<%= f.label :bio, "Bio", class: "form-label" %>
				<%= f.text_area :bio, class: "form-input small" %>
			</div>
			
			<div class="form-row">
				<%= f.label :password, "Password", class: "form-label" %>
				<%= f.password_field  :password, class: "form-input" %>
			</div>
			
			<div class="form-row">
				<%= f.label :password_confirmation, "Confirm?", class: "form-label" %>
				<%= f.password_field :password_confirmation, class: "form-input" %>
			</div>
		
			<br /><%= f.submit "Create Account", class: "btn btn-large bttn centered"%>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb


<% provide(:title, @user.first_name + ' ' + @user.last_name) %>

<!-- Tailored "What's New" horizontal across top -->
<div class="floating-grid3">
	<div class="cell">
		<!-- Profile photo -->
		<div class="content-panel">
			<%= profile_image @user.id %>
		</div>
		
		<!-- Most popular story -->
		<% unless @popular.nil? %>
			<div class="content-panel">
				<div class="list-item-even">
					<div class="pull-right" style="text-align: right">
						<div>Reads   <%= @popular.read_count %></div>
						<div>Downloads   <%= @popular.downloaded %></div>
						<div>Donated   <%= donated_s @popular.id %></div>
					</div>
					<a href="/works/<%= @popular.id %>" style="height: 100%; width: 100%;">
						<div class="pull-left"></div>
						<div><%= @popular.title %></div>
					</a>
					<div style="width: 90%;"><%= @popular.blurb %></div>
				</div>
			</div>
		<% end %>
	</div>
	<div class="cell">
		<!-- Pen Name -->
		<div class="content-panel">
			<%= yield :title %>
		</div>
		
		<!-- User Bio -->
		<div class="content-panel">
			<%= @user.bio %>
		</div>
		
		<!-- User Since -->
		<div class="content-panel">
			User Since <%= @user.created_at.year %>
		</div>
		
		<!-- Stories -->
		<div class="content-panel">
			<% if signed_in? %>
				<a href="<%= stories_path %>"><%= image_tag "MyStories.png" %></a>
			<% else %>
				<a href="/search/<%= @user.id.to_s %>"><%= image_tag "MyStories.png"%></a>
			<% end %>
		</div>
	</div>
	
	
	<div class="cell">
		<!-- User stats -->
		<div class="content-panel">
			<div>Stories Published: <%= @user.works.length %></div>
			<div>Total Reads: <%= @user.works.sum(:read_count) %></div>
			<div>Amount Donated: <%= donated @user.id %></div>
			<div>Amount Recieved: <%= recieved @user.id %></div>
		</div>
		
		<!-- Donate -->
		<div class="content-panel">
			<% unless @popular.nil? %>
				<a href="/donate/<%= @popular.id %>"><%= image_tag "Donate.png"%></a>
			<% end %>
		</div>
	</div>
	
	
	
</div>


app/views/users/stories.html.erb
<%= provide(:title, @user.first_name + ' ' + @user.last_name + ' | Stories')%>
<%= page_title_tag "MyStoriesGraphx.png"%>

<%= render 'works/works_edit_list' %>