config/routes.rb
TreeHouse::Application.routes.draw do
  resources :donations

  resources :works

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'site#home'

  match '/testsub', to: 'site#testsub', via: 'get'
  match '/subscribe', to: 'site#subscribe', via: 'get'
  match '/subscribe_email', to: 'site#subscribe_email', via: 'post'
  match '/unsubscribe' , to: 'site#unsubscribe', via: 'get'
  match '/unsubscribe_email', to: 'site#unsubsribe_email', via: 'post'
    match '/published', to: 'site#published',    via: 'get'
    match '/photography', to: 'site#photography', via: 'get'
      match '/photography/:series_name', to: 'site#photography_detail', via: 'get'
      match '/photo/:series_name/:name', to: 'site#photo', via: 'get'

    match '/painting', to: 'site#painting', via: 'get'
      match '/painting/:name', to: 'site#painting_detail', via: 'get'

    match '/drawing', to: 'site#drawing', via: 'get'

    match '/parastories', to: 'site#parastories', via: 'get'
      match '/parastories/:name', to: 'site#parastories', via: 'get'

    match '/shortstories', to: 'site#shortstories', via: 'get'
      match '/shortstories/:name', to: 'site#short_detail', via: 'get'

    match '/poetry', to: 'site#poetry', via: 'get'
      match '/poetry/:name', to: 'site#poetry_detail', via: 'get'

    match '/thankyou', to: 'site#thankyou', via: 'get'

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :work
  
  validates :amount, presence: true
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  # GET /donations
  # GET /donations.json
  #def index
  #  @donations = Donation.all
  #end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
    
    @donation.approved = false
    @donation.site_donation = false
    
    unless params[:type].nil?
      if params[:type].to_i == 0
        @donation.site_donation = true
      else
        @work = Work.find(params[:type])
        @donation.work_id = @work.id
        @donation.user_id = @work.user.id
      end
    end
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)
    logger.debug 'donation_params' + donation_params.inspect
    logger.debug 'params' + params.inspect

    respond_to do |format|
      if @donation.save
        # TODO: Craft redirect-to-paypal url here
        PayPal::SDK.configure(
          :mode      => "sandbox",  # Set "live" for production
          :app_id    => "APP-80W284485P519543T",
          :username  => "michaelkelly322-facilitator_api1.gmail.com",
          :password  => "1394740509",
          :signature => "AJcd4zryQhQ2ZgcZLiVoqM93-q0wA2dcbJdAmqurm0ecK0o7QXYV-dxB" )
        
        @api = PayPal::SDK::AdaptivePayments.new
        
        # Build request object
        @pay = @api.build_pay({
          :actionType => "PAY",
          :cancelUrl => "http://localhost:3000/donations/cancel/#{@donation.id}",
          :currencyCode => "USD",
          :feesPayer => "SENDER",
          #:ipnNotificationUrl => "http://localhost:3000/samples/adaptive_payments/ipn_notify",
          :receiverList => {
            :receiver => [{
              :amount => @donation.amount,
              :email => "test-author@gmail.com" }] },
          :returnUrl => "http://localhost:3000/donations/approve/#{@donation.id}" })
        
        # Make API call & get response
        @response = @api.pay(@pay)
        if @response.success?
          @url = @api.payment_url(@response)
          
          format.html { render 'donation_forward' }
        else
          format.html { render action: 'new', notice: 'Error communicating with Paypal' }
        end
        
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @donation }
      else
        format.html { render action: 'new' }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  def cancel
    unless params[:id].nil?
      don = Donation.find(params[:id])
      
      unless don.nil?
        don.delete
      end
    end
    
    redirect_to root_path
  end

  def approve
    unless params[:id].nil?
      don = Donation.find(params[:id])
      
      don.approved = true
      if don.save
        if signed_in?
          current_user.update_attribute(:donated, current_user.donated + don.amount)
        end
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:amount, :site_donation, :approved, :user_id, :work_id)
    end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/approve.html.erb
<h1>Thank You!</h1>

app/views/donations/donation_forward.html.erb
<a id='paypal-link' href=<%= @url %> target='_blank'>link</a>
<script>
	$(document).ready(function() {
		window.open("<%= @url %>");
	});
</script>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<h1>Listing donations</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Site donation</th>
      <th>Approved</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.amount %></td>
        <td><%= donation.site_donation %></td>
        <td><%= donation.approved %></td>
        <td><%= link_to 'Show', donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<%= page_title_tag "donategraphx.png"%>

<div class="col-lg-4 col-md-5 col-sm-6 col-xs-6 centered content-panel">
	<%= form_for(@donation) do |f| %>
	  <% if @donation.errors.any? %>
	    <div id="error_explanation" style="">
	      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>
	
	      <ul>
	      <% @donation.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
		
		<%= hidden_field(:donation, :work_id, value: @donation.work_id) %>
		<%= hidden_field(:donation, :user_id, value: @donation.user_id) %>
		<%= hidden_field(:donation, :site_donation, value: @donation.site_donation) %>
		<%= hidden_field(:donation, :approved, value: @donation.approved) %>
		
	  <div class="form-row">
	    <%= f.label :amount, class: "form-label"%>
	    <%= f.text_field :amount, class: "form-input" %>
	  </div>
	  
	  <br /><%= f.submit "Proceed to Paypal", class: "btn btn-large bttn centered"%>
	  
	<% end %>
</div>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @donation.amount %>
</p>

<p>
  <strong>Site donation:</strong>
  <%= @donation.site_donation %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @donation.approved %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>